### PR TITLE
Add description for Touche SE, fix error in shanwan_ps3 and add desc for O&C

### PR DESCRIPTION
**Pull request by madskjeldgaard**

### CODE REVIEW

**Comment by madskjeldgaard** [comment]
Added an error fix to the desc of shanwan_ps3

**Comment by LFSaw** [comment]
@adcxyz you have one of those, right? could you maybe check if it works on osx as well?

**Comment by madskjeldgaard** [comment]
Hi, since this is still open I hope it's okay if I add another controller description here.

**Comment by adcxyz** [comment]
> @adcxyz you have one of those, right? could you maybe check if it works on osx as well?

touche no, shanwan don't know, likely at uni ... will check next time there.

// @madskjeldgaard 
> Hi, since this is still open I hope it's okay if I add another controller description here.

It is easier to keep track of PRs later when they are smaller, but  no problem now. 
Thanks, they look very good, very friendly doc and examples, just how it should be!

**Pull request merged**
