### PR TITLE
class library: inline functions if possible

### PR DESCRIPTION
**Pull request by telephon**
When keeping ````Post Inline Warnings```` checked, there are inline failure warnings. This commit moves variables out of the functions so they can be inlined.

### CODE REVIEW

**Comment by LFSaw** [comment]
thanks for this, @telephon ! 


Would love to merge but your commit does also 

+ change posting methods, (Use of "MKtl" instead of "MIDIMktl" was a delibarate choice), and 
+ removes temporarily out-commented (?) lines in MIDIMktlDevice. (They are there to keep reminding us of missing implementations, so please keep them.)

Would be good to have those at least as separate commits (if not PRs) so that cherry-picking is manageable.

**Comment by telephon** [comment]
> change posting methods, (Use of "MKtl" instead of "MIDIMktl" was a delibarate choice), and
  >removes temporarily out-commented (?) lines in MIDIMktlDevice. (They are there to keep reminding us of missing implementations, so please keep them.)

This is *really* strange. I could swear I haven't touched them, I wouldn't know why.  I'll fix this.

**Comment by telephon** [comment]
um, not sure, I probably messed this all up. Never mind, maybe another time ...

**Comment by LFSaw** [comment]
also, the current branch we're working on is https://github.com/ModalityTeam/Modality-toolkit/tree/MKtl_refactor_test2 (I know, this is a bit weird...), so your fixes should be best to have there. 

:)

**Comment by telephon** [comment]
hm, ok. Anyway, not a big deal, next week I'll try and figure it out.

**Comment by LFSaw** [comment]
maybe it is good to wait until next week, yes... we're currently having two branches (master and MKtl_refactor_test2) that are kindof diverging... I sent a message to the list to clarify about this.

**Comment by adcxyz** [comment]
redid these fixes for refactor_test2 branch in 5359587, closing PR.

**Pull request closed without merging**
