### PR TITLE
Mktl no device

### PR DESCRIPTION
**Pull request by sensestage**
This branch allows for creating an MKtl without opening the device, even if it is attached.

It is branched of the cc14bit branch though, so merging this pull request also means merging the cc14bit.

### CODE REVIEW

**Comment by LFSaw** [comment]
I added the later flag because we should deal with this once #295 is merged.

**Comment by LFSaw** [comment]
unfortunately, it is quite difficult to see what you changed (among other things because the 14bit changes are part of this patch). Could you point me to the right places, please?

**Comment by adcxyz** [comment]
This branch allows for creating an MKtl without opening the device
IIUC, only the commit to MKtl.sc is creating an MKtl without opening the device.
Why restrict this PR to just that single file?

**Comment by LFSaw** [comment]
@adcxyz do you mean " Why not restrict this PR to just that single file?"

**Comment by adcxyz** [comment]
@LFSaw - yes exactly, I meant  " Why ***NOT*** restrict this PR to just that single file?"
sorry for the confusion.

**Comment by LFSaw** [comment]
@sensestage ,  could you please restrict this PR to just the files important for it by branching from master instead of your own branch?

**Comment by LFSaw** [comment]
since #295 is merged now, would you mind having a look at this, @adcxyz ?

**Comment by adcxyz** [comment]
@sensestage - should be simple, only the changes to MKtl.sc are needed for the noDevice option, and those look fine to me. so please renew as advices by @LFSaw.

**Pull request merged**
